### ISSUE TITLE
Include stach_extensions.py in fds

### ISSUE THREAD

**Issue by katsuya-horiuchi** [factset/analyticsapi-engines-python-sdk#2]
I think the title says it.
Can we include [stach_extensions.py](https://github.com/factset/analyticsapi-engines-python-sdk/blob/master/Utilities/examples/stach_extensions.py) in `fds` rather than in examples directory?

An end-user should be able to import functions like the below, making it easier to use. Otherwise the code base will be messy.
```python
from fds.utils import generate_excel, generate_table
```

**Comment by saigiridhar21** [comment]
Thanks for the suggestion. We are tracking this task internally and will let you know once we release it.
