### ISSUE TITLE
Mock urllib3 in unit testing

### ISSUE THREAD

**Issue by katsuya-horiuchi** [factset/analyticsapi-engines-python-sdk#3]
Can you mock urlllib3 in unit tests?
Obviously I don't have access to API key outside of work, thus I can't run tests.
By mocking HTTP response, however, you should be able to run tests without actually calling API.

**Comment by saigiridhar21** [comment]
Using our sandbox environment, you can run the tests. For that, please generate API key at [developer portal](https://developer.factset.com/) using your FactSet's .net email ID and use `https://api-sandbox.factset.com` as [base url](https://github.com/factset/analyticsapi-engines-python-sdk/blob/master/Utilities/tests/common_parameters.py#L9).
