### ISSUE TITLE
Add proxy settings for fds.analyticsapi.engines.Configuration()

### ISSUE THREAD

**Issue by dmpe** [factset/analyticsapi-engines-python-sdk#4]
Otherwise describe how to set https proxy so that connection can be established. 

Thanks.

**Comment by saigiridhar21** [comment]
Please refer to this [link](https://github.com/factset/analyticsapi-engines-python-sdk/blob/master/Utilities/examples/multiple_engines_example.py#L61). Let us know if it doesn't work.

**Comment by dmpe** [comment]
Thank you. I will close it now and will reopen if needed.
